# Generated by Django 4.1.4 on 2023-11-06 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_task_assigned_to_task_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 17, 47, 12, 605592, tzinfo=datetime.timezone.utc)),
        ),
    ]
