# Generated by Django 4.1.4 on 2023-11-19 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_adminnotification_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 17, 38, 38, 438087, tzinfo=datetime.timezone.utc)),
        ),
    ]
