# Generated by Django 4.1.4 on 2023-11-26 14:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_additioninformationforuser_github_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additioninformationforuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 14, 51, 51, 953799, tzinfo=datetime.timezone.utc)),
        ),
    ]
