# Generated by Django 4.1.4 on 2023-11-26 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_additioninformationforuser_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 15, 4, 16, 686174, tzinfo=datetime.timezone.utc)),
        ),
    ]
